--- name:default

##################################
##Stream Aligner Properties
##################################
# minimum system time in s between two status readings
stream_aligner_status_period: 0.1
# minimum time, in s, between two sequential samples arrive on model_velocity
model_velocity_period: 0.001
# minimum time, in s, between two sequential samples arrive on measured_velocity
measured_velocity_period: 0.001
# maximum latency, in seconds, of the stream aligner. The aligner will start dropping samples if the difference between the last output and last input is greater than this
aggregator_max_latency: 6.0
#################################
# define degree of freedom to be evaluate
#dof: :SURGE



--- name:surge
# define degree of freedom to be evaluate
dof: :SURGE

--- name:sway
# define degree of freedom to be evaluate
dof: :SWAY

--- name:heave
# define degree of freedom to be evaluate
dof: :HEAVE

--- name:roll
# define degree of freedom to be evaluate
dof: :ROLL

--- name:pitch
# define degree of freedom to be evaluate
dof: :PITCH

--- name:yaw
# define degree of freedom to be evaluate
dof: :YAW

