--- name:dagon
# Matrix of trhuster. Identifie the forces and torques aplied for each of n trhuster
TCM:
  rows: 6
  cols: 5
  data:
  - 0.0 ## dive_tail
  - 0.0
  - -1.0
  - 0.0
  - -0.39
  - 0.0
  - 0.0 ## dive_head
  - 0.0
  - -1.0
  - 0.0
  - 0.16
  - 0.0
  - 1.0 ## surge_left
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - -0.38
  - 1.0 ## surge_right
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.38
  - 0.0 ## sway_tail
  - 1.0
  - 0.0
  - 0.06
  - 0.0
  - -0.55
# If left empty, uses RAW by default
control_modes: 
  - SPEED
  - SPEED
  - SPEED
  - SPEED
  - SPEED
# no documentation available for this property
metadata:
  metadata: []
  properties: []
  input_ports: []
  output_ports: []
# Names of the thrusters
# Leave empty to use no names
names: ["dive_tail", "dive_head", "surge_left", "surge_right", "sway_tail"]
# The amount of actuators the vehicle has
number_of_thruster: 5
# In case the control mode is PWM, used to convert the signal into DC Voltage
thrusterVoltage: 0.0
# Convert thruster signal into forces, in negative direction. Should have the size of amount_of_actuators
thruster_coefficients_Neg:
  data: 
  - 0.01541807
  - 0.01541807
  - 0.083426624
  - 0.083426624
  - 0.01992116    # Opposite polarite, from observation    
# Convert thruster signal into forces, in positive direction. Should have the size of amount_of_actuators
thruster_coefficients_Pos:
  data: 
  - 0.01992116
  - 0.01992116 
  - 0.113126622
  - 0.113126622
  - 0.01541807     # Opposite polarite, from observation  
# Offset error of thruster forces found in motion identification. Added to the resulted forces
offset_forces:
  data: 
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0


--- name:flatfish
# Matrix of trhuster. Identifie the forces and torques aplied for each of n trhuster
TCM:
  rows: 6
  cols: 6
  data:
  -  1.0 # left_surge
  -  0.0
  -  0.0
  -  0.0
  -  0.0
  -  0.392
  -  -1.0 # right_surge
  -  0.0
  -  0.0
  -  0.0
  -  0.0 
  -  0.392
  -  0.0 # sway_front
  -  -1.0
  -  0.0
  -  0.0
  -  0.0
  -  -0.587
  -  0.0 # sway_rear
  -  -1.0
  -  0.0
  -  0.0
  -  0.0
  -  0.819
  -  0.0 # heave_front
  -  0.0
  -  1.0
  -  0.0
  -  -0.447
  -  0.0
  -  0.0 # heave_rear
  -  0.0
  -  1.0
  -  0.0
  -  0.464
  -  0.0 
# If left empty, uses RAW by default
control_modes: 
  - SPEED
  - SPEED
  - SPEED
  - SPEED
  - SPEED
  - SPEED
# no documentation available for this property
metadata:
  metadata: []
  properties: []
  input_ports: []
  output_ports: []
# Names of the thrusters
# Leave empty to use no names
names: ['surge_left', 'surge_right', 'sway_front', 'sway_rear', 'heave_front', 'heave_rear']
# The amount of actuators the vehicle has
number_of_thruster: 6
# In case the control mode is PWM, used to convert the signal into DC Voltage
thrusterVoltage: 0.0
# Convert thruster signal into forces, in negative direction. Should have the size of amount_of_actuators
thruster_coefficients_Neg:
  data: 
  - 0.00006698667 # from [rad/s] to [N]
  - 0.00006698667
  - 0.00006698667
  - 0.00006698667
  - 0.00006698667 
  - 0.00006698667   
# Convert thruster signal into forces, in positive direction. Should have the size of amount_of_actuators
thruster_coefficients_Pos:
  data: 
  - 0.00006698667
  - 0.00006698667
  - 0.00006698667
  - 0.00006698667
  - 0.00006698667 
  - 0.00006698667
# Offset error of thruster forces found in motion identification. Added to the resulted forces
offset_forces:
  data: 
  - 0.976 #0.14 #0.976
  - -0.348915
  - 11.4521 #11.4 #12.698 #12.4264
  - 0.0
  - 0.0
  - 0.0727 #0.2509 #0.090945 #-0.08854 #0.037 #0.0106326 #0.11483
  
--- name:flatfish_new
# Matrix of trhuster. Identifie the forces and torques aplied for each of n trhuster
TCM:
  rows: 6
  cols: 6
  data:
  -  1.0 # left_surge
  -  0.0
  -  0.0
  -  0.0
  -  0.0
  -  0.392
  -  -1.0 # right_surge
  -  0.0
  -  0.0
  -  0.0
  -  0.0 
  -  0.392
  -  0.0 # sway_front
  -  -1.0
  -  0.0
  -  0.0
  -  0.0
  -  -0.537 #-0.500 #-0.587
  -  0.0 # sway_rear
  -  -1.0
  -  0.0
  -  0.0
  -  0.0
  -  0.869 #0.906 #0.819
  -  0.0 # heave_front
  -  0.0
  -  1.0
  -  0.0
  -  -0.397 #-0.36 #-0.447
  -  0.0
  -  0.0 # heave_rear
  -  0.0
  -  1.0
  -  0.0
  -  0.514 #0.531 #0.464
  -  0.0 
# If left empty, uses RAW by default
control_modes: 
  - SPEED
  - SPEED
  - SPEED
  - SPEED
  - SPEED
  - SPEED
# no documentation available for this property
metadata:
  metadata: []
  properties: []
  input_ports: []
  output_ports: []
# Names of the thrusters
# Leave empty to use no names
names: ['surge_left', 'surge_right', 'sway_front', 'sway_rear', 'heave_front', 'heave_rear']
# The amount of actuators the vehicle has
number_of_thruster: 6
# In case the control mode is PWM, used to convert the signal into DC Voltage
thrusterVoltage: 0.0
# Convert thruster signal into forces, in negative direction. Should have the size of amount_of_actuators
thruster_coefficients_Neg:
  data: 
  - 0.00006698667 # from [rad/s] to [N]
  - 0.00006698667
  - 0.00006698667
  - 0.00006698667
  - 0.00006698667 
  - 0.00006698667   
# Convert thruster signal into forces, in positive direction. Should have the size of amount_of_actuators
thruster_coefficients_Pos:
  data: 
  - 0.00006698667
  - 0.00006698667
  - 0.00006698667
  - 0.00006698667
  - 0.00006698667 
  - 0.00006698667
# Offset error of thruster forces found in motion identification. Added to the resulted forces
offset_forces:
  data: 
  - 0.913384 #0.913384 #0.976
  - -0.348915
  - 12.698 #12.4264
  - 0.0
  - 0.0
  - 0.135 #0.0906326 #0.11483  

