--- name:dagon
# Defines if the control signal is PWM, RPM or EFFORT.
control_mode: :EFFORT
# no documentation available for this property
metadata:
  metadata: []
  properties: []
  input_ports: []
  output_ports: []
# Parameters of the motion model.
model_parameters:
  ctrl_order: 6
  samplingtime: 0.1
  sim_per_cycle: 10
  massMatrix:
    data:
    - 421.0     # surge
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 10000.0     # sway
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 0.0
    - 10000.0     # heave
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 0.0
    - 0.0
    - 10000.0       # roll
    - 0.0
    - 0.0       
    - 0.0       #### 
    - 0.0
    - 0.0
    - 0.0
    - 10000.0       # pitch
    - 0.0
    - 0.0       #### 
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 40.5       # yaw
  coriolisMatrix:
    data:
    - 0.0     # surge
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 0.0     # sway
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 0.0
    - 0.0     # heave
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 0.0
    - 0.0
    - 0.0       # roll
    - 0.0
    - 0.0       
    - 0.0       #### 
    - 0.0
    - 0.0
    - 0.0
    - 0.0       # pitch
    - 0.0
    - 0.0       #### 
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0       # yaw
  linDampMatrix:        
    data:
    - 9.3     # surge
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 11.0     # sway
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 0.0
    - 11.0     # heave
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 0.0
    - 0.0
    - 7.0       # roll
    - 0.0
    - 0.0       
    - 0.0       #### 
    - 0.0
    - 0.0
    - 0.0
    - 7.0       # pitch
    - 0.0
    - 0.0       #### 
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 1.24       # yaw
  quadDampMatrix:
    data:
    - 2.7     # surge
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 2.0     # sway
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 0.0
    - 2.0     # heave
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 0.0
    - 0.0
    - 2.0       # roll
    - 0.0
    - 0.0       
    - 0.0       #### 
    - 0.0
    - 0.0
    - 0.0
    - 2.0       # pitch
    - 0.0
    - 0.0       #### 
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.35       # yaw
  thruster_control_matrix:
    rows: 6
    cols: 6
    data:
    - 1.0    # surge
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0    # sway
    - 1.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0    # heave
    - 0.0
    - 1.0
    - 0.0
    - 0.0
    - 0.0   
    - 0.0    # roll
    - 0.0
    - 0.0
    - 1.0
    - 0.0
    - 0.0
    - 0.0    # pitch
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    - 0.0   
    - 0.0    # yaw
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 1.0    
  distance_body2centerofbuoyancy:
    data:
    - 0.0
    - 0.0
    - 0.0
  distance_body2centerofgravity:
    data:
    - 0.0
    - 0.0
    - 0.0
  uwv_mass: 0.0  
  uwv_volume: 0.0
  uwv_float: false
  waterDensity: 998.2
  gravity: 9.81
  thrusterVoltage: [0.0]
  thruster_coefficients_pwm:
  - positive: 0.0
    negative: 0.0
  linear_thruster_coefficients_pwm:
  - positive: 0.0
    negative: 0.0
  square_thruster_coefficients_pwm:
  - positive: 0.0
    negative: 0.0
  thruster_coefficient_rpm:
  - positive: 0.0
    negative: 0.0
  initial_condition:
  - 0.0 # position
  - 0.0
  - -3.0
  - 0.0 # euler orientation
  - 0.0
  - 0.0
  - 0.0 # linear velocity
  - 0.0
  - 0.0
  - 0.0 # angular velocity
  - 0.0
  - 0.0
# Name of the source frame.
source_frame: ''
# Name of the target frame.
target_frame: ''
# Velocity uncertainty values. This values are integrated in order to obtain the pose uncertainty
velocity_uncertainty:
  data:
  - 2.0e-323
  - 0.1
  - 5.0e-323
  - 0.0
  - 0.0
  - 0.0
  
  
--- name:dagon_input_trhuster
# Defines if the control signal is PWM, RPM or EFFORT.
control_mode: :RPM
# no documentation available for this property
metadata:
  metadata: []
  properties: []
  input_ports: []
  output_ports: []
# Parameters of the motion model.
model_parameters:
  ctrl_order: 5
  samplingtime: 0.01
  sim_per_cycle: 10
  massMatrix:
    data:
    - 200.0     # surge
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 10000.0     # sway
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 0.0
    - 10000.0     # heave
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 0.0
    - 0.0
    - 1000.0       # roll
    - 0.0
    - 0.0       
    - 0.0       #### 
    - 0.0
    - 0.0
    - 0.0
    - 1000.0       # pitch
    - 0.0
    - 0.0       #### 
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 1000.0       # yaw
  coriolisMatrix:
    data:
    - 0.0     # surge
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 0.0     # sway
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 0.0
    - 0.0     # heave
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 0.0
    - 0.0
    - 0.0       # roll
    - 0.0
    - 0.0       
    - 0.0       #### 
    - 0.0
    - 0.0
    - 0.0
    - 0.0       # pitch
    - 0.0
    - 0.0       #### 
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0       # yaw
  linDampMatrix:        
    data:
    - 11.0     # surge
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 11.0     # sway
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 0.0
    - 11.0     # heave
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 0.0
    - 0.0
    - 7.0       # roll
    - 0.0
    - 0.0       
    - 0.0       #### 
    - 0.0
    - 0.0
    - 0.0
    - 7.0       # pitch
    - 0.0
    - 0.0       #### 
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 7.0       # yaw
  quadDampMatrix:
    data:
    - 2.0     # surge
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 2.0     # sway
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 0.0
    - 2.0     # heave
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 0.0
    - 0.0
    - 2.0       # roll
    - 0.0
    - 0.0       
    - 0.0       #### 
    - 0.0
    - 0.0
    - 0.0
    - 2.0       # pitch
    - 0.0
    - 0.0       #### 
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 2.0       # yaw
  thruster_control_matrix:
    rows: 6
    cols: 5
    data:
    - 0.0 ## dive_tail
    - 0.0
    - -1.0
    - 0.0
    - -0.39
    - 0.0
    - 0.0 ## dive_head
    - 0.0
    - -1.0
    - 0.0
    - 0.16
    - 0.0
    - 1.0 ## surge_left
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - -0.38
    - 1.0 ## surge_right
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.38
    - 0.0 ## sway_tail
    - 1.0
    - 0.0
    - 0.06
    - 0.0
    - -0.55
  distance_body2centerofbuoyancy:
    data:
    - 0.0
    - 0.0
    - 0.0
  distance_body2centerofgravity:
    data:
    - 0.0
    - 0.0
    - 0.0
  uwv_mass: 0.0
  uwv_volume: 0.0
  uwv_float: false
  waterDensity: 998.2
  gravity: 9.81
  thrusterVoltage: [0.0]
  thruster_coefficients_pwm:
  - positive: 0.0
    negative: 0.0
  linear_thruster_coefficients_pwm:
  - positive: 0.0
    negative: 0.0
  square_thruster_coefficients_pwm:
  - positive: 0.0
    negative: 0.0
  thruster_coefficient_rpm:
  - positive: 0.01992116
    negative: 0.01541807
  - positive: 0.01992116
    negative: 0.01541807
  - positive: 0.113126622
    negative: 0.083426624
  - positive: 0.113126622
    negative: 0.083426624
  - positive: 0.01541807     # Opposite polarite, from observation 
    negative: 0.01992116    # Opposite polarite, from observation         
  initial_condition:
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
# Name of the source frame.
source_frame: ''
# Name of the target frame.
target_frame: ''
# Velocity uncertainty values. This values are integrated in order to obtain the pose uncertainty
velocity_uncertainty:
  data:
  - 2.0e-323
  - 0.1
  - 5.0e-323
  - 0.0
  - 0.0
  - 0.0  
  
  
--- name:dagon_step33
# Defines if the control signal is PWM, RPM or EFFORT.
control_mode: :EFFORT
# no documentation available for this property
metadata:
  metadata: []
  properties: []
  input_ports: []
  output_ports: []
# Parameters of the motion model.
model_parameters:
  ctrl_order: 6
  samplingtime: 0.033
  sim_per_cycle: 10
  massMatrix:
    data:
    - 200.0     # surge
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 10000.0     # sway
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 0.0
    - 10000.0     # heave
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 0.0
    - 0.0
    - 10000.0       # roll
    - 0.0
    - 0.0       
    - 0.0       #### 
    - 0.0
    - 0.0
    - 0.0
    - 10000.0       # pitch
    - 0.0
    - 0.0       #### 
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 10000.0       # yaw
  coriolisMatrix:
    data:
    - 0.0     # surge
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 0.0     # sway
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 0.0
    - 0.0     # heave
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 0.0
    - 0.0
    - 0.0       # roll
    - 0.0
    - 0.0       
    - 0.0       #### 
    - 0.0
    - 0.0
    - 0.0
    - 0.0       # pitch
    - 0.0
    - 0.0       #### 
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0       # yaw
  linDampMatrix:        
    data:
    - 10.0     # surge
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 11.0     # sway
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 0.0
    - 11.0     # heave
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 0.0
    - 0.0
    - 7.0       # roll
    - 0.0
    - 0.0       
    - 0.0       #### 
    - 0.0
    - 0.0
    - 0.0
    - 7.0       # pitch
    - 0.0
    - 0.0       #### 
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 7.0       # yaw
  quadDampMatrix:
    data:
    - 2.0     # surge
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 2.0     # sway
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 0.0
    - 2.0     # heave
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 0.0
    - 0.0
    - 2.0       # roll
    - 0.0
    - 0.0       
    - 0.0       #### 
    - 0.0
    - 0.0
    - 0.0
    - 2.0       # pitch
    - 0.0
    - 0.0       #### 
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 2.0       # yaw
  thruster_control_matrix:
    rows: 6
    cols: 6
    data:
    - 1.0    # surge
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0    # sway
    - 1.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0    # heave
    - 0.0
    - 1.0
    - 0.0
    - 0.0
    - 0.0   
    - 0.0    # roll
    - 0.0
    - 0.0
    - 1.0
    - 0.0
    - 0.0
    - 0.0    # pitch
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    - 0.0   
    - 0.0    # yaw
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 1.0    
  distance_body2centerofbuoyancy:
    data:
    - 0.0
    - 0.0
    - 0.0
  distance_body2centerofgravity:
    data:
    - 0.0
    - 0.0
    - 0.0
  uwv_mass: 0.0
  uwv_volume: 0.0
  uwv_float: false
  waterDensity: 998.2
  gravity: 9.81
  thrusterVoltage: [0.0]
  thruster_coefficients_pwm:
  - positive: 0.0
    negative: 0.0
  linear_thruster_coefficients_pwm:
  - positive: 0.0
    negative: 0.0
  square_thruster_coefficients_pwm:
  - positive: 0.0
    negative: 0.0
  thruster_coefficient_rpm:
  - positive: 0.0
    negative: 0.0
  initial_condition:
  - 0.0 # position
  - 0.0
  - -3.0
  - 0.0 # euler orientation
  - 0.0
  - 0.0
  - 0.0 # linear velocity
  - 0.0
  - 0.0
  - 0.0 # angular velocity
  - 0.0
  - 0.0
# Name of the source frame.
source_frame: ''
# Name of the target frame.
target_frame: ''
# Velocity uncertainty values. This values are integrated in order to obtain the pose uncertainty
velocity_uncertainty:
  data:
  - 2.0e-323
  - 0.1
  - 5.0e-323
  - 0.0
  - 0.0
  - 0.0
  
  
--- name:flatfish
# Defines if the control signal is PWM, RPM or EFFORT.
control_mode: :EFFORT
# no documentation available for this property
metadata:
  metadata: []
  properties: []
  input_ports: []
  output_ports: []
# Parameters of the motion model.
model_parameters:
  ctrl_order: 6
  samplingtime: 0.1
  sim_per_cycle: 10
  massMatrix:
    data:
    - 890.282 #909.8 #890.282 #851.051     # surge
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 10000.0 #1002.0     # sway
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 0.0
    - 3206.85 #5400 # 1521.45 #1511.53     # heave
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 0.0
    - 0.0
    - 10000.0       # roll
    - 0.0
    - 0.0       
    - 0.0       #### 
    - 0.0
    - 0.0
    - 0.0
    - 10000.0       # pitch
    - 0.0
    - 0.0       #### 
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 317.594 #343.36 #301.603 #334.411 #302.176 #301.603 #302.176      # yaw
  coriolisMatrix:
    data:
    - 0.0     # surge
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 0.0     # sway
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 0.0
    - 0.0     # heave
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 0.0
    - 0.0
    - 0.0       # roll
    - 0.0
    - 0.0       
    - 0.0       #### 
    - 0.0
    - 0.0
    - 0.0
    - 0.0       # pitch
    - 0.0
    - 0.0       #### 
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0       # yaw
  linDampMatrix:        
    data:
    - 38.823 #61.01 #38.823 #39.9237     # surge
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 1000.0 #-232.321     # sway
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 0.0
    - 101.765 #28 #31.408 #-70.2901     # heave
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 0.0
    - 0.0
    - 10000.0       # roll
    - 0.0
    - 0.0       
    - 0.0       #### 
    - 0.0
    - 0.0
    - 0.0
    - 10000.0       # pitch
    - 0.0
    - 0.0       #### 
    - 0.0
    - 0.0
    - 0.0
    - 10.295 #11.787 #26.9277 #1.75011 #42.3 #26.9277 #42.3       # yaw
  quadDampMatrix:
    data:
    - 6.78911 #10.85 #6.78911 #6.48232     # surge
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 10000.0 #6712.52     # sway
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 0.0
    - -754.859 #1.6 #2.246 #1911.21    # heave
    - 0.0
    - 0.0
    - 0.0
    - 0.0       #### 
    - 0.0
    - 0.0
    - 10000.0       # roll
    - 0.0
    - 0.0       
    - 0.0       #### 
    - 0.0
    - 0.0
    - 0.0
    - 10000.0       # pitch
    - 0.0
    - 0.0       #### 
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 154.281 #174.916 #279.394 #317.219 #2.33468 #279.394 #2.33       # yaw
  thruster_control_matrix:
    rows: 6
    cols: 6
    data:
    - 1.0    # surge
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0    # sway
    - 1.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0    # heave
    - 0.0
    - 1.0
    - 0.0
    - 0.0
    - 0.0   
    - 0.0    # roll
    - 0.0
    - 0.0
    - 1.0
    - 0.0
    - 0.0
    - 0.0    # pitch
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    - 0.0   
    - 0.0    # yaw
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 1.0    
  distance_body2centerofbuoyancy:
    data:
    - 0.0
    - 0.0
    - 0.0
  distance_body2centerofgravity:
    data:
    - 0.0
    - 0.0
    - 0.0
  uwv_mass: 0.0 #300.0
  uwv_volume: 0.0 #0.301786845 #0.299295102 #0.301786845 #0.001245872  
  uwv_float: false
  waterDensity: 998.2
  gravity: 9.81
  thrusterVoltage: [0.0]
  thruster_coefficients_pwm:
  - positive: 0.0
    negative: 0.0
  linear_thruster_coefficients_pwm:
  - positive: 0.0
    negative: 0.0
  square_thruster_coefficients_pwm:
  - positive: 0.0
    negative: 0.0
  thruster_coefficient_rpm:
  - positive: 0.00006698667
    negative: 0.00006698667
  initial_condition:
  - 0.0 # position
  - 0.0
  - -3.0
  - 0.0 # euler orientation
  - 0.0
  - 0.0
  - 0.0 # linear velocity
  - 0.0
  - 0.0
  - 0.0 # angular velocity
  - 0.0
  - 0.0
# Name of the source frame.
source_frame: ''
# Name of the target frame.
target_frame: ''
# Velocity uncertainty values. This values are integrated in order to obtain the pose uncertainty
velocity_uncertainty:
  data:
  - 2.0e-323
  - 0.1
  - 5.0e-323
  - 0.0
  - 0.0
  - 0.0
    
